# Generated by Django 5.0.4 on 2024-04-08 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Your Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, null=True, verbose_name="Your Email"
                    ),
                ),
                ("subject", models.CharField(max_length=100, null=True)),
                ("message", models.TextField(null=True)),
            ],
            options={
                "verbose_name_plural": "Contacts",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="home_contac_name_10e56e_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Project Name",
                    ),
                ),
                (
                    "project_slug",
                    models.SlugField(
                        blank=True, null=True, verbose_name="Project Slug"
                    ),
                ),
                (
                    "project_img",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to="projects_img",
                        verbose_name="Project Image",
                    ),
                ),
                (
                    "project_desc",
                    models.TextField(
                        blank=True, null=True, verbose_name="Project Description"
                    ),
                ),
                ("docu_url_on", models.BooleanField(default=False)),
                ("docu_url", models.URLField(blank=True, verbose_name="Document URL")),
                ("git_url_on", models.BooleanField(default=False)),
                ("git_url", models.URLField(blank=True, verbose_name="Git URL")),
                ("video_url_on", models.BooleanField(default=False)),
                ("video_url", models.URLField(blank=True, verbose_name="Video URL")),
                ("done", models.BooleanField(default=False)),
                ("date_done", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Projects",
                "ordering": ["project_name"],
                "indexes": [
                    models.Index(
                        fields=["project_name"], name="home_projec_project_e28b1d_idx"
                    ),
                    models.Index(
                        fields=["project_img"], name="home_projec_project_24c9aa_idx"
                    ),
                    models.Index(
                        fields=["project_desc"], name="home_projec_project_10b8a5_idx"
                    ),
                    models.Index(
                        fields=["docu_url", "git_url", "video_url"],
                        name="home_projec_docu_ur_ae0e46_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.FileField(upload_to="resume")),
                ("linkedin_link", models.URLField(blank=True)),
                ("github_link", models.URLField(blank=True)),
                ("google_link", models.URLField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Portfolio",
                "indexes": [
                    models.Index(
                        fields=["linkedin_link", "github_link", "google_link"],
                        name="home_portfo_linkedi_0012ca_idx",
                    )
                ],
            },
        ),
    ]
